In [ ]:
import numpy as np

# 1. Collaborative Filtering, Kernels, Linear Regression

In [ ]:
U = np.array([6, 0, 3, 6])
V = np.array([4, 2, 1])

X = U.reshape((-1, 1)) @ V.reshape((1, -1))
print(X)

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


In [ ]:
Y = np.array([[5, 0, 7],
              [0, 2, 0],
              [4, 0, 0],
              [0, 3, 6]])
mask = Y > 0

err = 1/2 * np.sum(((Y - X)**2)[mask])
reg = 1/2 * (U @ U + V @ V)

print(f"Square Error: {err}, Reg: {reg}")

Square Error: 255.5, Reg: 51.0


In [ ]:
lam = 1
Y @ V / (np.ma.array(np.tile(np.diag(V.reshape((-1, 1)) @ V.reshape((1, -1))), (U.shape[0],1)), mask=~mask).sum(axis=1).data+lam)

array([1.5       , 0.8       , 0.94117647, 2.        ])