In [46]:
import numpy as np

# Problem 1. Linear Classification

## Q1

In [47]:
xs = np.array([[0, 0],
               [2, 0],
               [3, 0],
               [0, 2],
               [2, 2],
               [5, 1],
               [5, 2],
               [2, 4],
               [4, 4],
               [5, 5]])

ys = np.array([-1, -1, -1, -1, -1, 1, 1, 1, 1, 1])

mistakes = np.array([1, 9, 10, 5, 9, 11, 0, 3, 1, 1])

In [48]:
theta0 = np.sum(ys * mistakes)
print(f"theta0 = {theta0}")

theta  = np.sum(xs * ys.reshape((-1, 1)) * mistakes.reshape((-1, 1)), axis=0)
print(f"theta  = {theta}")

theta0 = -18
theta  = [4 4]


## Q3

In [49]:
from sklearn.svm import LinearSVC

model = LinearSVC().fit(xs, ys)

print(f"theta0 = {model.intercept_}")
print(f"theta  = {model.coef_}")

model.predict(xs)

theta0 = [-1.50554186]
theta  = [[0.33559893 0.35592594]]


array([-1, -1, -1, -1, -1,  1,  1,  1,  1,  1])

## Q4

In [50]:
theta0 = model.intercept_
theta  = model.coef_

xs @ theta.reshape((-1, 1)) + theta0

array([[-1.50554186],
       [-0.834344  ],
       [-0.49874507],
       [-0.79368999],
       [-0.12249213],
       [ 0.52837872],
       [ 0.88430466],
       [ 0.58935974],
       [ 1.2605576 ],
       [ 1.95208247]])

## Q5

In [51]:
def hinge(x):
  return np.maximum(0, 1-x)

In [52]:
theta  = np.ones(2)
theta0 = -5

hinge(ys * (xs @ theta + theta0))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Q6

In [53]:
theta  = theta / 2
theta0 = theta0 / 2

hinge(ys * (xs @ theta + theta0))

array([0. , 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0. , 0. ])

# Problem 2. Kernel Methods

## Q2

In [54]:
xs = np.array([[0, 0],
               [2, 0],
               [1, 1],
               [0, 2],
               [3, 3],
               [4, 1],
               [5, 2],
               [1, 4],
               [4, 4],
               [5, 5]])

ys = np.array([-1, -1, -1, -1, -1, 1, 1, 1, 1, 1])

mistakes = np.array([1, 65, 11, 31, 72, 30, 0, 21, 4, 15])

In [55]:
def phi(xs):
  N = len(xs)
  transform = np.zeros((N, 3))
  
  transform[:, 0] = xs[:, 0]**2
  transform[:, 1] = np.sqrt(2) * xs[:, 0] * xs[:, 1]
  transform[:, 2] = xs[:, 1]**2
  return transform

In [56]:
theta0 = np.sum(ys * mistakes)
print(f"theta0 = {theta0}")

theta  = np.sum(phi(xs) * ys.reshape((-1, 1)) * mistakes.reshape((-1, 1)), axis=0)
print(f"theta  = {theta}")

theta0 = -110
theta  = [ 21.       -22.627417  22.      ]


## Q3

In [57]:
(ys * (phi(xs) @ theta + theta0)) > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# Problem 4

## Q4

In [58]:
np.linalg.matrix_rank(np.array([[1. -1],
                                [-1, 1]]))

1

In [59]:
np.linalg.matrix_rank(np.array([[1, 0],
                                [0, 1]]))

2

In [60]:
np.linalg.matrix_rank(np.array([[1, 1],
                                [-1, -1]]))

1